version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
      POSTGRES_DB: login_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Host port changed to avoid conflict
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: login_db
      DATABASE_USER: django_user
      DATABASE_PASSWORD: django_pass

volumes:
  pgdata:

# docker tag login_project_web:latest jhalak0412/login_project_web:1.0.0
# docker push jhalak0412/login_project_web:1.0.0